Repository Markusgp/Untangle, pull requests merged in 2023-04, with the labels that each got.

#86 Package expansion
  src/Model/Parse.js
  src/utils.js
Labels: feature

#90 Minor bug fixes
  src/Flow.js
  src/utils.js
Labels: bug

#97 Edge weight scaling
  src/EdgeCalculations.js
  src/Flow.js
  src/Model/ClassTree.js
  src/data/Class.json
  src/data/Extensions.json
  src/data/GenericInitialization.json
  src/data/GenericInstantiation.json
  src/data/Implementations.json
  src/data/Initialization.json
  src/data/Instantiation.json
  src/data/Interface.json
  src/utils.js
Labels: feature

#98 Small improvements
  .gitignore
  README.md
  docker-commands.txt
  docker-run.sh
  public/Untangle.svg
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  run-docker.sh
  run-unix.sh
  run.sh
  src/App.test.js
  src/Model/Parse.js
  src/codeql-data/Class.json
  src/codeql-data/Extensions.json
  src/codeql-data/GenericInitialization.json
  src/codeql-data/GenericInstantiation.json
  src/codeql-data/Implementations.json
  src/codeql-data/Initialization.json
  src/codeql-data/Instantiation.json
  src/codeql-data/Interface.json
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: bug, documentation
